### ISSUE TITLE
ramda-debug on the browser

### ISSUE THREAD

**Issue by lube** [sebinsua/ramda-debug#13]
Is it possible to use this module on the browser?

I tried to browserify it but I keep finding problems with dependencies and requires.

**Comment by lube** [comment]
I managed to understand browserify enought to require the service into my custom service :D

**Comment by sebinsua** [comment]
Cool. Tell me if you find any problems, or want to make any improvements - it was mostly an experimental debugging tool so I'd like to see what other's might come up with to improve it.

**Comment by lube** [comment]
I am trying to introduce my own types into the debugging tool, trying to wrap the side effect thay may happen, Im not sure if Im on the right track, does this make sense?

```
function Entity (state) {
    this.state = state
}

someEntity = new Entity(1);

mylibrary = {update: function(entity, newValue) 
                                     {   entity.state = newValue; return entity; } }

look.wrap(mylibrary);

f1 = function () { some_promise.then(mylibrary.update(someEntity)) }

f2 = look.fov(f1);

f2();
```

```
                                                          `
```

**Comment by sebinsua** [comment]
```
#!/usr/bin/env node
'use strict';

var look = require('ramda-debug').on();

function Entity (state) {
    this.state = state;
}

var someEntity = new Entity(1);

var mylibrary = {
  update: function update(entity, newValue) {
    entity.state = newValue;
    return entity;
  }
};

var f1 = function () {
  var promiseReturnsTwo = Promise.resolve(2);
  return promiseReturnsTwo.then(function (v) {
    return mylibrary.update(someEntity, v);
  });
};

mylibrary = look.wrap(mylibrary);
f1 = look('f1', f1);

f1();
```

It seems that `look.fov` does not currently play nicely with functions that return promises. It will switch off the debugging before it can return anything. Additionally wrapping a function with just a `look` will show empty objects as the promises are not resolved yet.

<img width="334" alt="screen shot 2016-02-29 at 00 21 21" src="https://cloud.githubusercontent.com/assets/152098/13383033/2a999d4a-de7a-11e5-8fed-ad0f31d612be.png">

So it partially works, but does not work for functions that return promises.
