### ISSUE TITLE
Turn on/off debugging

### ISSUE THREAD

**Issue by ThomasCrevoisier** [sebinsua/ramda-debug#2]
Great work on your lib !

I just wondering is there a way to turn enable/disable printing infos ? For example, I might wrap Ramda with your tool at the beginning of a file but I may be interested in debugging specific parts of my code.

**Comment by sebinsua** [comment]
I thought I had some working code which did this with `look.on()` and `look.off()` however it looks like it doesn't actually work so I'll take a look over the next couple of days. Not sure that's a the API I'll settle on either - we shall see.

I'm currently [in the midst of writing another library](https://github.com/sebinsua/jstruct) and that is going to need careful debugging so I'm hoping I can use that to drive this project forwards, too.

**Comment by ThomasCrevoisier** [comment]
It seems like `look.on()` and `look.off()` don't have any effect on wrapped functions resulting of using `look.wrap`. I'll take a look at it tomorrow.
Btw, if you want help on something, I'd be glad to help ^^

UPDATE :
After looking at the code, when you wrap a function with `look()` the wrapped function will keep the same value for `this.enabled` and using `look.on()` and `look.off()` won't change it after the function is wrapped.

**Comment by sebinsua** [comment]
I made some changes.

`look.on()` and `look.off()` should now work, and they return `look` itself. There is also a `look.enable()` that takes a boolean. By default `look` is not enabled when it is returned by the library.

However the better way of using the library is now probably with `look.fov()`.

``` javascript
var R = require('ramda');
var look = require('ramda-debug');

R = look.wrap(R);

var getResult = look.fov(function getResult(a, b, c, d) {
  var curry4 = R.curryN(4);
  var curriedAbc = curry4(function abc(a, b, c, d) {
    return a + b + c + d;
  });
  var curriedFn = look('curriedAbc', curriedAbc);

  var fn1 = curriedFn(a);
  var fn2 = fn1(b);
  var fn3  = fn2(c);
  var number = fn3(d);

  return number;
});

console.log(getResult(1, 2, 3, 4));
```

**Comment by sebinsua** [comment]
Published [ramda-debug@0.1.1](https://www.npmjs.com/package/ramda-debug).

**Comment by sebinsua** [comment]
Closing. Tell me if there are any more problems - and feel free to pitch in with a PR if you fix any yourself. :)

**Comment by ThomasCrevoisier** [comment]
Okay, thanks ! I haven't finished testing yet but this looks good, I will let you know if I have comments :)
